name: "Shared Setup"
description: "Checkout, download artifacts and setup JDK"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Download source artifact
      uses: actions/download-artifact@v4
      with:
        name: source
        path: .
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'